# Generated by Django 5.1.4 on 2024-12-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemName", models.TextField(max_length=255)),
                ("itemCount", models.IntegerField()),
                ("Expires_on", models.DateField()),
                ("Description", models.TextField(max_length=500)),
            ],
        ),
    ]
