# Generated by Django 5.1.4 on 2024-12-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="itemName",
            field=models.TextField(max_length=125),
        ),
    ]
