# Generated by Django 5.1.4 on 2024-12-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventory_itemname"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="status",
            field=models.IntegerField(default=1),
        ),
    ]
